// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageSteam.proto

package com.rastakiki.protobufstream.protobuf;

public final class MessageSteam {
    private MessageSteam() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface TupleLengthOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required int64 length = 1;

        /**
         * <code>required int64 length = 1;</code>
         */
        boolean hasLength();

        /**
         * <code>required int64 length = 1;</code>
         */
        long getLength();
    }

    /**
     * Protobuf type {@code com.rastakiki.protobufstream.protobuf.TupleLength}
     */
    public static final class TupleLength extends
            com.google.protobuf.GeneratedMessage
            implements TupleLengthOrBuilder {
        // Use TupleLength.newBuilder() to construct.
        private TupleLength(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private TupleLength(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final TupleLength defaultInstance;

        public static TupleLength getDefaultInstance() {
            return defaultInstance;
        }

        public TupleLength getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private TupleLength(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            length_ = input.readInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.rastakiki.protobufstream.protobuf.MessageSteam.internal_static_com_rastakiki_protobufstream_protobuf_TupleLength_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.rastakiki.protobufstream.protobuf.MessageSteam.internal_static_com_rastakiki_protobufstream_protobuf_TupleLength_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength.class, com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength.Builder.class);
        }

        public static com.google.protobuf.Parser<TupleLength> PARSER =
                new com.google.protobuf.AbstractParser<TupleLength>() {
                    public TupleLength parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new TupleLength(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<TupleLength> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        // required int64 length = 1;
        public static final int LENGTH_FIELD_NUMBER = 1;
        private long length_;

        /**
         * <code>required int64 length = 1;</code>
         */
        public boolean hasLength() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int64 length = 1;</code>
         */
        public long getLength() {
            return length_;
        }

        private void initFields() {
            length_ = 0L;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasLength()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt64(1, length_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, length_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.rastakiki.protobufstream.protobuf.TupleLength}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLengthOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.rastakiki.protobufstream.protobuf.MessageSteam.internal_static_com_rastakiki_protobufstream_protobuf_TupleLength_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.rastakiki.protobufstream.protobuf.MessageSteam.internal_static_com_rastakiki_protobufstream_protobuf_TupleLength_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength.class, com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength.Builder.class);
            }

            // Construct using com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                length_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.rastakiki.protobufstream.protobuf.MessageSteam.internal_static_com_rastakiki_protobufstream_protobuf_TupleLength_descriptor;
            }

            public com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength getDefaultInstanceForType() {
                return com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength.getDefaultInstance();
            }

            public com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength build() {
                com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength buildPartial() {
                com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength result = new com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.length_ = length_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength) {
                    return mergeFrom((com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength other) {
                if (other == com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength.getDefaultInstance())
                    return this;
                if (other.hasLength()) {
                    setLength(other.getLength());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasLength()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.rastakiki.protobufstream.protobuf.MessageSteam.TupleLength) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            // required int64 length = 1;
            private long length_;

            /**
             * <code>required int64 length = 1;</code>
             */
            public boolean hasLength() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required int64 length = 1;</code>
             */
            public long getLength() {
                return length_;
            }

            /**
             * <code>required int64 length = 1;</code>
             */
            public Builder setLength(long value) {
                bitField0_ |= 0x00000001;
                length_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 length = 1;</code>
             */
            public Builder clearLength() {
                bitField0_ = (bitField0_ & ~0x00000001);
                length_ = 0L;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.rastakiki.protobufstream.protobuf.TupleLength)
        }

        static {
            defaultInstance = new TupleLength(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.rastakiki.protobufstream.protobuf.TupleLength)
    }

    public interface TupleOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required int64 id = 1;

        /**
         * <code>required int64 id = 1;</code>
         */
        boolean hasId();

        /**
         * <code>required int64 id = 1;</code>
         */
        long getId();

        // required string value = 2;

        /**
         * <code>required string value = 2;</code>
         */
        boolean hasValue();

        /**
         * <code>required string value = 2;</code>
         */
        java.lang.String getValue();

        /**
         * <code>required string value = 2;</code>
         */
        com.google.protobuf.ByteString
        getValueBytes();
    }

    /**
     * Protobuf type {@code com.rastakiki.protobufstream.protobuf.Tuple}
     */
    public static final class Tuple extends
            com.google.protobuf.GeneratedMessage
            implements TupleOrBuilder {
        // Use Tuple.newBuilder() to construct.
        private Tuple(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private Tuple(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final Tuple defaultInstance;

        public static Tuple getDefaultInstance() {
            return defaultInstance;
        }

        public Tuple getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Tuple(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            id_ = input.readInt64();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            value_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.rastakiki.protobufstream.protobuf.MessageSteam.internal_static_com_rastakiki_protobufstream_protobuf_Tuple_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.rastakiki.protobufstream.protobuf.MessageSteam.internal_static_com_rastakiki_protobufstream_protobuf_Tuple_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple.class, com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple.Builder.class);
        }

        public static com.google.protobuf.Parser<Tuple> PARSER =
                new com.google.protobuf.AbstractParser<Tuple>() {
                    public Tuple parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new Tuple(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<Tuple> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        // required int64 id = 1;
        public static final int ID_FIELD_NUMBER = 1;
        private long id_;

        /**
         * <code>required int64 id = 1;</code>
         */
        public boolean hasId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required int64 id = 1;</code>
         */
        public long getId() {
            return id_;
        }

        // required string value = 2;
        public static final int VALUE_FIELD_NUMBER = 2;
        private java.lang.Object value_;

        /**
         * <code>required string value = 2;</code>
         */
        public boolean hasValue() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string value = 2;</code>
         */
        public java.lang.String getValue() {
            java.lang.Object ref = value_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    value_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string value = 2;</code>
         */
        public com.google.protobuf.ByteString
        getValueBytes() {
            java.lang.Object ref = value_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                value_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            id_ = 0L;
            value_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasValue()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt64(1, id_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getValueBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, id_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getValueBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.rastakiki.protobufstream.protobuf.Tuple}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.rastakiki.protobufstream.protobuf.MessageSteam.TupleOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.rastakiki.protobufstream.protobuf.MessageSteam.internal_static_com_rastakiki_protobufstream_protobuf_Tuple_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.rastakiki.protobufstream.protobuf.MessageSteam.internal_static_com_rastakiki_protobufstream_protobuf_Tuple_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple.class, com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple.Builder.class);
            }

            // Construct using com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                id_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000001);
                value_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.rastakiki.protobufstream.protobuf.MessageSteam.internal_static_com_rastakiki_protobufstream_protobuf_Tuple_descriptor;
            }

            public com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple getDefaultInstanceForType() {
                return com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple.getDefaultInstance();
            }

            public com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple build() {
                com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple buildPartial() {
                com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple result = new com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.id_ = id_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.value_ = value_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple) {
                    return mergeFrom((com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple other) {
                if (other == com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple.getDefaultInstance()) return this;
                if (other.hasId()) {
                    setId(other.getId());
                }
                if (other.hasValue()) {
                    bitField0_ |= 0x00000002;
                    value_ = other.value_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasId()) {

                    return false;
                }
                if (!hasValue()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.rastakiki.protobufstream.protobuf.MessageSteam.Tuple) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            // required int64 id = 1;
            private long id_;

            /**
             * <code>required int64 id = 1;</code>
             */
            public boolean hasId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required int64 id = 1;</code>
             */
            public long getId() {
                return id_;
            }

            /**
             * <code>required int64 id = 1;</code>
             */
            public Builder setId(long value) {
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 id = 1;</code>
             */
            public Builder clearId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                id_ = 0L;
                onChanged();
                return this;
            }

            // required string value = 2;
            private java.lang.Object value_ = "";

            /**
             * <code>required string value = 2;</code>
             */
            public boolean hasValue() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required string value = 2;</code>
             */
            public java.lang.String getValue() {
                java.lang.Object ref = value_;
                if (!(ref instanceof java.lang.String)) {
                    java.lang.String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    value_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string value = 2;</code>
             */
            public com.google.protobuf.ByteString
            getValueBytes() {
                java.lang.Object ref = value_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    value_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string value = 2;</code>
             */
            public Builder setValue(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                value_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string value = 2;</code>
             */
            public Builder clearValue() {
                bitField0_ = (bitField0_ & ~0x00000002);
                value_ = getDefaultInstance().getValue();
                onChanged();
                return this;
            }

            /**
             * <code>required string value = 2;</code>
             */
            public Builder setValueBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                value_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.rastakiki.protobufstream.protobuf.Tuple)
        }

        static {
            defaultInstance = new Tuple(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.rastakiki.protobufstream.protobuf.Tuple)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_com_rastakiki_protobufstream_protobuf_TupleLength_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_com_rastakiki_protobufstream_protobuf_TupleLength_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_com_rastakiki_protobufstream_protobuf_Tuple_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_com_rastakiki_protobufstream_protobuf_Tuple_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\022messageSteam.proto\022%com.rastakiki.prot" +
                        "obufstream.protobuf\"\035\n\013TupleLength\022\016\n\006le" +
                        "ngth\030\001 \002(\003\"\"\n\005Tuple\022\n\n\002id\030\001 \002(\003\022\r\n\005value" +
                        "\030\002 \002(\t"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_com_rastakiki_protobufstream_protobuf_TupleLength_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_com_rastakiki_protobufstream_protobuf_TupleLength_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_com_rastakiki_protobufstream_protobuf_TupleLength_descriptor,
                                new java.lang.String[]{"Length",});
                        internal_static_com_rastakiki_protobufstream_protobuf_Tuple_descriptor =
                                getDescriptor().getMessageTypes().get(1);
                        internal_static_com_rastakiki_protobufstream_protobuf_Tuple_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_com_rastakiki_protobufstream_protobuf_Tuple_descriptor,
                                new java.lang.String[]{"Id", "Value",});
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
